DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: False

SAM_VERSION: 'vit_b'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 10
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 0
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.248046875, P=0.46317335963249207 R=0.3987990915775299 F1=0.42858240008354187
# ======= road ======
# Best threshold 0.363525390625, P=0.7002477049827576 R=0.7432668209075928 F1=0.7211161851882935
# ======= topo ======
# Best threshold 0.499267578125, P=0.9713579416275024 R=0.9679416418075562 F1=0.9696467518806458

ITSC_THRESHOLD: 0.248
ROAD_THRESHOLD: 0.364
TOPO_THRESHOLD: 0.500
# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16