DATASET: 'cityscale'

# IN1k + MAE only
NO_SAM: True

SAM_VERSION: 'vit_b'
SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 10
BASE_LR: 0.001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False

# TOPONET
# sample per patch
TOPO_SAMPLE_NUM: 512
TOPONET_VERSION: 'normal'

# Inference
INFER_BATCH_SIZE: 64
SAMPLE_MARGIN: 64
INFER_PATCHES_PER_EDGE: 16

# ======= keypoint ======
# Best threshold 0.4189453125, P=0.0 R=0.0 F1=nan <- this is just a failure, just use 0.1 to at least get some predictions
# ======= road ======
# Best threshold 0.172607421875, P=0.26732638478279114 R=0.45330917835235596 F1=0.3363184332847595
# ======= topo ======
# Best threshold 0.4375, P=0.9535335302352905 R=0.9491331577301025 F1=0.9513282775878906

ITSC_THRESHOLD: 0.1
ROAD_THRESHOLD: 0.173
TOPO_THRESHOLD: 0.438

# pixels
ITSC_NMS_RADIUS: 8
ROAD_NMS_RADIUS: 16
NEIGHBOR_RADIUS: 64
MAX_NEIGHBOR_QUERIES: 16