BASE_LR: 0.001
BATCH_SIZE: 16
DATASET: cityscale
DATA_WORKER_NUM: 1
ENCODER_LORA: false
ENCODER_LR_FACTOR: 0.1
FOCAL_LOSS: false
FREEZE_ENCODER: false
INFER_BATCH_SIZE: 64
INFER_PATCHES_PER_EDGE: 16
ITSC_NMS_RADIUS: 8
ITSC_THRESHOLD: 0.248
MAX_NEIGHBOR_QUERIES: 16
NEIGHBOR_RADIUS: 64
NO_SAM: false
PATCH_SIZE: 512
ROAD_NMS_RADIUS: 16
ROAD_THRESHOLD: 0.364
SAMPLE_MARGIN: 64
SAM_CKPT_PATH: /home/datadisk/evaluation/models/SAM/SAM-road/sam_vit_b_01ec64.pth
SAM_VERSION: vit_b
TOPONET_VERSION: normal
TOPO_SAMPLE_NUM: 512
TOPO_THRESHOLD: 0.5
TRAIN_EPOCHS: 10
USE_SAM_DECODER: false
