SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
PATCH_SIZE: 1024
BATCH_SIZE: 2
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 10
BASE_LR: 0.0001
FREEZE_ENCODER: False
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: False
FOCAL_LOSS: False
USE_SAM_DECODER: False