SAM_CKPT_PATH: 'sam_ckpts/sam_vit_b_01ec64.pth'
PATCH_SIZE: 512
BATCH_SIZE: 16
DATA_WORKER_NUM: 1
TRAIN_EPOCHS: 15
BASE_LR: 0.001
FREEZE_ENCODER: True
ENCODER_LR_FACTOR: 0.1
ENCODER_LORA: True
LORA_RANK: 4
FOCAL_LOSS: False
USE_SAM_DECODER: True